version: '3'
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: qwe@123
    ports:
      - '3307:3306'

  spring-boot-demo:
    # 确保 `Dockerfile` 位于与 `docker-compose.yml` 文件相同的目录中
    build:
      context: .
    # 先请求拉取远程镜像，失败后再使用 `build` 配置构建本地镜像
    image: spring-boot-demo:latest
    container_name: spring-boot-demo
    restart: always
    ports:
      - '8081:8080'
    volumes:
      # 使得配置文件可放在主机中：`/Users/wxj/Downloads/application.yml`
      - /Users/wxj/Downloads:/opt/config
    depends_on:
      - db
    # 这里的 `command` 仅为演示需要
    command: ['sh', '-c', 'sleep 10; java -jar /opt/spring-boot-demo.jar']


# 启动命令：docker compose up -d
