const ELLIPSIS = '…'

const URL_QUERY_KEY_QUERY = 'query'
const URL_QUERY_KEY_PAGE_NUM = 'page'
const URL_QUERY_KEY_PAGE_SIZE = 'size'

export { ELLIPSIS, URL_QUERY_KEY_PAGE_NUM, URL_QUERY_KEY_PAGE_SIZE, URL_QUERY_KEY_QUERY }
