const ELLIPSIS = '…'

const URL_QUERY_KEY_QUERY = 'q'
const URL_QUERY_KEY_PAGE_NUM = 'p'
const URL_QUERY_KEY_PAGE_SIZE = 's'
const URL_QUERY_KEY_ORDER_BY = 'b'
const URL_QUERY_KEY_ORDER = 'o'

export {
  ELLIPSIS,
  URL_QUERY_KEY_ORDER,
  URL_QUERY_KEY_ORDER_BY,
  URL_QUERY_KEY_PAGE_NUM,
  URL_QUERY_KEY_PAGE_SIZE,
  URL_QUERY_KEY_QUERY
}
