# 部署时, 可提取部分需要修改的配置项到 `application.yml`，并置于与 Jar 同级目录的 `config` 子目录下即可
server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: qwe@123
  datasource:
    url: jdbc:mysql://127.0.0.1:3306
    username: root
    password: qwe@123
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  main:
    banner-mode: off
mybatis:
  type-handlers-package: net.wuxianjie.springbootweb.shared.mybatis
  mapper-locations: classpath:mappers/*.xml
  configuration:
    call-setters-on-nulls: true
    shrink-whitespaces-in-sql: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
