# 部署时, 可提取部分需要修改的配置项到 `application.yml`，并置于与 Jar 同级目录的 `config` 子目录下即可
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: ENC(ANOf5l6jbyPQN8dk9dHy9C8sd0ZhowraFYXInEcG8am+ybTJhQwxR+MKN/bl54Z4)
    password: ENC(H0yLbj9m4Y9UpTSt4spGMqmOR/pvL0yDFCKp04gGBJCa+C+vgj27kXST+nCzP72z)
  data:
    redis:
      host: localhost
      port: 6379
      password: ENC(/hSZu9OFtlFU1xHCzThMmTYbu+e8JD8G9wF+9d1ygtf7hD/tyFEvjcZU92xgvGgp)
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  main:
    banner-mode: off
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
